

modLoader="javafml"
loaderVersion="[37,)"
license="All Rights Reserved"

[[mods]]
modId="buildwand"
version="${version}"
displayName="Build Wand"
description='''
A build wand mod for Minecraft 1.17.1
'''

[[dependencies.buildwand]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildwand]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"

