
modLoader="javafml"
loaderVersion="[26,)"

[[mods]]
modId="buildwand"
version="2.0.1"
displayName="Build Wand"
description='''
Oyuncuların bir alanı seçip, otomatik olarak belirtilen malzemelerle doldurmasına olanak tanıyan bir mod
'''
authors="LorNople"
credits="Replit-AI"

[[dependencies.buildwand]]
    modId="forge"
    mandatory=true
    versionRange="[26,29)"
    ordering="NONE"
    side="BOTH"

[[dependencies.buildwand]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2,1.14.5)"
    ordering="NONE"
    side="BOTH"
